package com.xeinebiu.anplayer.plugin.media.extractor.model

import android.net.Uri
import com.xeinebiu.anplayer.plugin.media.extractor.enum.MediaFormat
import com.xeinebiu.anplayer.plugin.media.extractor.model.descriptor.ExtractorContent
import java.util.Locale

open class Subtitle(
    val displayLanguageName: String,
    val extension: String,
    val format: MediaFormat,
    val isAutoGenerated: Boolean,
    val locale: Locale,
    val uri: Uri
) : ExtractorContent()
