package com.xeinebiu.anplayer.plugin.base.media.extractor.model

import android.net.Uri
import com.xeinebiu.anplayer.plugin.base.media.extractor.enum.MediaFormat
import java.util.*

class Subtitle(
    val displayLanguageName: String,
    val extension: String,
    val format: MediaFormat,
    val isAutoGenerated: Boolean,
    val locale: Locale,
    val uri: Uri
)
